# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPARX5) += sparx5_pcb125.dtb
dtb-$(CONFIG_ARCH_SPARX5) += sparx5_appl_pcb134.dtb sparx5_appl_pcb134_emmc.dtb
dtb-$(CONFIG_ARCH_SPARX5) += sparx5_appl_pcb135.dtb sparx5_appl_pcb135_emmc.dtb
dtb-$(CONFIG_ARCH_SPARX5) += \
	sparx5_pcb134.dtb sparx5_pcb134_emmc.dtb \
	sparx5_pcb135.dtb sparx5_pcb135_emmc.dtb
dtb-$(CONFIG_ARCH_LAN969X) += lan969x_sr.dtb lan969x_ev23x71a.dtb \
	lan969x_appl_ev23x71a.dtb lan969x_pcb10001.dtb \
	lan969x_ev89p81a.dtb lan969x_appl_ev89p81a.dtb
