// Copyright (c) 2004-2020 Microchip Technology Inc. and its subsidiaries.
// SPDX-License-Identifier: MIT

/* This file is autogenerated by cml-utils 2021-02-04 13:07:36 +0100.
 * Commit ID: 0359c23857fee4dc44d5a77219b74b8cb979e0c1 (dirty)
 */

#ifndef _LAN966X_SPI_REGS_SR_H_
#define _LAN966X_SPI_REGS_SR_H_


#define LAN966X_BUILD_ID_REG GCB_BUILDID
#define LAN966X_BUILD_ID 1610532836

enum lan966x_target {
	TARGET_GCB = 25,
	TARGET_QSPI = 41,
	NUM_TARGETS = 65
};

#define __REG(...)    __VA_ARGS__

/*      GCB:GPIO:GPIO_ALT */
#define GCB_GPIO_ALT(r)           __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 96, r, 3, 4)

/*      GCB:GPIO:GPIO_ALT1 */
#define GCB_GPIO_ALT1(r)          __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 108, r, 3, 4)

/*      GCB:GPIO:GPIO_ALT2 */
#define GCB_GPIO_ALT2(r)          __REG(TARGET_GCB,\
					0, 1, 100, 0, 1, 180, 120, r, 3, 4)

#define GCB_GPIO_ALT2_G_ALT2(x)                  ((x) & GENMASK(13, 0))
#define GCB_GPIO_ALT2_G_ALT2_M                   GENMASK(13, 0)
#define GCB_GPIO_ALT2_G_ALT2_X(x)                ((x) & GENMASK(13, 0))

/*      QSPI:QSPI_REGS:QSPI_CR */
#define QSPI_QSPI_CR(t)           __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 0, 0, 1, 4)

#define QSPI_QSPI_CR_LASTXFER(x)                 (((x) << 24) & GENMASK(24, 24))
#define QSPI_QSPI_CR_LASTXFER_M                  GENMASK(24, 24)
#define QSPI_QSPI_CR_LASTXFER_X(x)               (((x) & GENMASK(24, 24)) >> 24)

#define QSPI_QSPI_CR_RTOUT(x)                    (((x) << 10) & GENMASK(10, 10))
#define QSPI_QSPI_CR_RTOUT_M                     GENMASK(10, 10)
#define QSPI_QSPI_CR_RTOUT_X(x)                  (((x) & GENMASK(10, 10)) >> 10)

#define QSPI_QSPI_CR_STTFR(x)                    (((x) << 9) & GENMASK(9, 9))
#define QSPI_QSPI_CR_STTFR_M                     GENMASK(9, 9)
#define QSPI_QSPI_CR_STTFR_X(x)                  (((x) & GENMASK(9, 9)) >> 9)

#define QSPI_QSPI_CR_UPDCFG(x)                   (((x) << 8) & GENMASK(8, 8))
#define QSPI_QSPI_CR_UPDCFG_M                    GENMASK(8, 8)
#define QSPI_QSPI_CR_UPDCFG_X(x)                 (((x) & GENMASK(8, 8)) >> 8)

#define QSPI_QSPI_CR_SWRST(x)                    (((x) << 7) & GENMASK(7, 7))
#define QSPI_QSPI_CR_SWRST_M                     GENMASK(7, 7)
#define QSPI_QSPI_CR_SWRST_X(x)                  (((x) & GENMASK(7, 7)) >> 7)

#define QSPI_QSPI_CR_SRFRSH(x)                   (((x) << 5) & GENMASK(5, 5))
#define QSPI_QSPI_CR_SRFRSH_M                    GENMASK(5, 5)
#define QSPI_QSPI_CR_SRFRSH_X(x)                 (((x) & GENMASK(5, 5)) >> 5)

#define QSPI_QSPI_CR_STPCAL(x)                   (((x) << 4) & GENMASK(4, 4))
#define QSPI_QSPI_CR_STPCAL_M                    GENMASK(4, 4)
#define QSPI_QSPI_CR_STPCAL_X(x)                 (((x) & GENMASK(4, 4)) >> 4)

#define QSPI_QSPI_CR_DLLOFF(x)                   (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_CR_DLLOFF_M                    GENMASK(3, 3)
#define QSPI_QSPI_CR_DLLOFF_X(x)                 (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_CR_DLLON(x)                    (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_CR_DLLON_M                     GENMASK(2, 2)
#define QSPI_QSPI_CR_DLLON_X(x)                  (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_CR_QSPIDIS(x)                  (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_CR_QSPIDIS_M                   GENMASK(1, 1)
#define QSPI_QSPI_CR_QSPIDIS_X(x)                (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_CR_QSPIEN(x)                   ((x) & GENMASK(0, 0))
#define QSPI_QSPI_CR_QSPIEN_M                    GENMASK(0, 0)
#define QSPI_QSPI_CR_QSPIEN_X(x)                 ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_MR */
#define QSPI_QSPI_MR(t)           __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 4, 0, 1, 4)

#define QSPI_QSPI_MR_DLYCS(x)                    (((x) << 24) & GENMASK(31, 24))
#define QSPI_QSPI_MR_DLYCS_M                     GENMASK(31, 24)
#define QSPI_QSPI_MR_DLYCS_X(x)                  (((x) & GENMASK(31, 24)) >> 24)

#define QSPI_QSPI_MR_DLYBCT(x)                   (((x) << 16) & GENMASK(23, 16))
#define QSPI_QSPI_MR_DLYBCT_M                    GENMASK(23, 16)
#define QSPI_QSPI_MR_DLYBCT_X(x)                 (((x) & GENMASK(23, 16)) >> 16)

#define QSPI_QSPI_MR_OENSD(x)                    (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_MR_OENSD_M                     GENMASK(15, 15)
#define QSPI_QSPI_MR_OENSD_X(x)                  (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_MR_PHYCR(x)                    (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_MR_PHYCR_M                     GENMASK(14, 14)
#define QSPI_QSPI_MR_PHYCR_X(x)                  (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_MR_QICMEN(x)                   (((x) << 13) & GENMASK(13, 13))
#define QSPI_QSPI_MR_QICMEN_M                    GENMASK(13, 13)
#define QSPI_QSPI_MR_QICMEN_X(x)                 (((x) & GENMASK(13, 13)) >> 13)

#define QSPI_QSPI_MR_NBBITS(x)                   (((x) << 8) & GENMASK(11, 8))
#define QSPI_QSPI_MR_NBBITS_M                    GENMASK(11, 8)
#define QSPI_QSPI_MR_NBBITS_X(x)                 (((x) & GENMASK(11, 8)) >> 8)

#define QSPI_QSPI_MR_TAMPCLR(x)                  (((x) << 7) & GENMASK(7, 7))
#define QSPI_QSPI_MR_TAMPCLR_M                   GENMASK(7, 7)
#define QSPI_QSPI_MR_TAMPCLR_X(x)                (((x) & GENMASK(7, 7)) >> 7)

#define QSPI_QSPI_MR_CSMODE(x)                   (((x) << 4) & GENMASK(5, 4))
#define QSPI_QSPI_MR_CSMODE_M                    GENMASK(5, 4)
#define QSPI_QSPI_MR_CSMODE_X(x)                 (((x) & GENMASK(5, 4)) >> 4)

#define QSPI_QSPI_MR_DQSDLYEN(x)                 (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_MR_DQSDLYEN_M                  GENMASK(3, 3)
#define QSPI_QSPI_MR_DQSDLYEN_X(x)               (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_MR_WDRBT(x)                    (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_MR_WDRBT_M                     GENMASK(2, 2)
#define QSPI_QSPI_MR_WDRBT_X(x)                  (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_MR_SMM(x)                      ((x) & GENMASK(0, 0))
#define QSPI_QSPI_MR_SMM_M                       GENMASK(0, 0)
#define QSPI_QSPI_MR_SMM_X(x)                    ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_RDR */
#define QSPI_QSPI_RDR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 8, 0, 1, 4)

#define QSPI_QSPI_RDR_RD(x)                      ((x) & GENMASK(15, 0))
#define QSPI_QSPI_RDR_RD_M                       GENMASK(15, 0)
#define QSPI_QSPI_RDR_RD_X(x)                    ((x) & GENMASK(15, 0))

/*      QSPI:QSPI_REGS:QSPI_TDR */
#define QSPI_QSPI_TDR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 12, 0, 1, 4)

#define QSPI_QSPI_TDR_TD(x)                      ((x) & GENMASK(15, 0))
#define QSPI_QSPI_TDR_TD_M                       GENMASK(15, 0)
#define QSPI_QSPI_TDR_TD_X(x)                    ((x) & GENMASK(15, 0))

/*      QSPI:QSPI_REGS:QSPI_ISR */
#define QSPI_QSPI_ISR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 16, 0, 1, 4)

#define QSPI_QSPI_ISR_TOUT_ISR(x)                (((x) << 17) & GENMASK(17, 17))
#define QSPI_QSPI_ISR_TOUT_ISR_M                 GENMASK(17, 17)
#define QSPI_QSPI_ISR_TOUT_ISR_X(x)              (((x) & GENMASK(17, 17)) >> 17)

#define QSPI_QSPI_ISR_RFRSHD_ISR(x)              (((x) << 16) & GENMASK(16, 16))
#define QSPI_QSPI_ISR_RFRSHD_ISR_M               GENMASK(16, 16)
#define QSPI_QSPI_ISR_RFRSHD_ISR_X(x)            (((x) & GENMASK(16, 16)) >> 16)

#define QSPI_QSPI_ISR_CSRA_ISR(x)                (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_ISR_CSRA_ISR_M                 GENMASK(15, 15)
#define QSPI_QSPI_ISR_CSRA_ISR_X(x)              (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_ISR_CSFA_ISR(x)                (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_ISR_CSFA_ISR_M                 GENMASK(14, 14)
#define QSPI_QSPI_ISR_CSFA_ISR_X(x)              (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_ISR_QITR_ISR(x)                (((x) << 13) & GENMASK(13, 13))
#define QSPI_QSPI_ISR_QITR_ISR_M                 GENMASK(13, 13)
#define QSPI_QSPI_ISR_QITR_ISR_X(x)              (((x) & GENMASK(13, 13)) >> 13)

#define QSPI_QSPI_ISR_QITF_ISR(x)                (((x) << 12) & GENMASK(12, 12))
#define QSPI_QSPI_ISR_QITF_ISR_M                 GENMASK(12, 12)
#define QSPI_QSPI_ISR_QITF_ISR_X(x)              (((x) & GENMASK(12, 12)) >> 12)

#define QSPI_QSPI_ISR_LWRA_ISR(x)                (((x) << 11) & GENMASK(11, 11))
#define QSPI_QSPI_ISR_LWRA_ISR_M                 GENMASK(11, 11)
#define QSPI_QSPI_ISR_LWRA_ISR_X(x)              (((x) & GENMASK(11, 11)) >> 11)

#define QSPI_QSPI_ISR_INSTRE_ISR(x)              (((x) << 10) & GENMASK(10, 10))
#define QSPI_QSPI_ISR_INSTRE_ISR_M               GENMASK(10, 10)
#define QSPI_QSPI_ISR_INSTRE_ISR_X(x)            (((x) & GENMASK(10, 10)) >> 10)

#define QSPI_QSPI_ISR_CSR_ISR(x)                 (((x) << 8) & GENMASK(8, 8))
#define QSPI_QSPI_ISR_CSR_ISR_M                  GENMASK(8, 8)
#define QSPI_QSPI_ISR_CSR_ISR_X(x)               (((x) & GENMASK(8, 8)) >> 8)

#define QSPI_QSPI_ISR_OVRES_ISR(x)               (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_ISR_OVRES_ISR_M                GENMASK(3, 3)
#define QSPI_QSPI_ISR_OVRES_ISR_X(x)             (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_ISR_TXEMPTY_ISR(x)             (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_ISR_TXEMPTY_ISR_M              GENMASK(2, 2)
#define QSPI_QSPI_ISR_TXEMPTY_ISR_X(x)           (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_ISR_TDRE_ISR(x)                (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_ISR_TDRE_ISR_M                 GENMASK(1, 1)
#define QSPI_QSPI_ISR_TDRE_ISR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_ISR_RDRF_ISR(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_ISR_RDRF_ISR_M                 GENMASK(0, 0)
#define QSPI_QSPI_ISR_RDRF_ISR_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_IER */
#define QSPI_QSPI_IER(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 20, 0, 1, 4)

#define QSPI_QSPI_IER_TOUT_IER(x)                (((x) << 17) & GENMASK(17, 17))
#define QSPI_QSPI_IER_TOUT_IER_M                 GENMASK(17, 17)
#define QSPI_QSPI_IER_TOUT_IER_X(x)              (((x) & GENMASK(17, 17)) >> 17)

#define QSPI_QSPI_IER_RFRSHD_IER(x)              (((x) << 16) & GENMASK(16, 16))
#define QSPI_QSPI_IER_RFRSHD_IER_M               GENMASK(16, 16)
#define QSPI_QSPI_IER_RFRSHD_IER_X(x)            (((x) & GENMASK(16, 16)) >> 16)

#define QSPI_QSPI_IER_CSRA_IER(x)                (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_IER_CSRA_IER_M                 GENMASK(15, 15)
#define QSPI_QSPI_IER_CSRA_IER_X(x)              (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_IER_CSFA_IER(x)                (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_IER_CSFA_IER_M                 GENMASK(14, 14)
#define QSPI_QSPI_IER_CSFA_IER_X(x)              (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_IER_QITR_IER(x)                (((x) << 13) & GENMASK(13, 13))
#define QSPI_QSPI_IER_QITR_IER_M                 GENMASK(13, 13)
#define QSPI_QSPI_IER_QITR_IER_X(x)              (((x) & GENMASK(13, 13)) >> 13)

#define QSPI_QSPI_IER_QITF_IER(x)                (((x) << 12) & GENMASK(12, 12))
#define QSPI_QSPI_IER_QITF_IER_M                 GENMASK(12, 12)
#define QSPI_QSPI_IER_QITF_IER_X(x)              (((x) & GENMASK(12, 12)) >> 12)

#define QSPI_QSPI_IER_LWRA_IER(x)                (((x) << 11) & GENMASK(11, 11))
#define QSPI_QSPI_IER_LWRA_IER_M                 GENMASK(11, 11)
#define QSPI_QSPI_IER_LWRA_IER_X(x)              (((x) & GENMASK(11, 11)) >> 11)

#define QSPI_QSPI_IER_INSTRE_IER(x)              (((x) << 10) & GENMASK(10, 10))
#define QSPI_QSPI_IER_INSTRE_IER_M               GENMASK(10, 10)
#define QSPI_QSPI_IER_INSTRE_IER_X(x)            (((x) & GENMASK(10, 10)) >> 10)

#define QSPI_QSPI_IER_CSR_IER(x)                 (((x) << 8) & GENMASK(8, 8))
#define QSPI_QSPI_IER_CSR_IER_M                  GENMASK(8, 8)
#define QSPI_QSPI_IER_CSR_IER_X(x)               (((x) & GENMASK(8, 8)) >> 8)

#define QSPI_QSPI_IER_OVRES_IER(x)               (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_IER_OVRES_IER_M                GENMASK(3, 3)
#define QSPI_QSPI_IER_OVRES_IER_X(x)             (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_IER_TXEMPTY_IER(x)             (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_IER_TXEMPTY_IER_M              GENMASK(2, 2)
#define QSPI_QSPI_IER_TXEMPTY_IER_X(x)           (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_IER_TDRE_IER(x)                (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_IER_TDRE_IER_M                 GENMASK(1, 1)
#define QSPI_QSPI_IER_TDRE_IER_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_IER_RDRF_IER(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_IER_RDRF_IER_M                 GENMASK(0, 0)
#define QSPI_QSPI_IER_RDRF_IER_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_IDR */
#define QSPI_QSPI_IDR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 24, 0, 1, 4)

#define QSPI_QSPI_IDR_TOUT_IDR(x)                (((x) << 17) & GENMASK(17, 17))
#define QSPI_QSPI_IDR_TOUT_IDR_M                 GENMASK(17, 17)
#define QSPI_QSPI_IDR_TOUT_IDR_X(x)              (((x) & GENMASK(17, 17)) >> 17)

#define QSPI_QSPI_IDR_RFRSHD_IDR(x)              (((x) << 16) & GENMASK(16, 16))
#define QSPI_QSPI_IDR_RFRSHD_IDR_M               GENMASK(16, 16)
#define QSPI_QSPI_IDR_RFRSHD_IDR_X(x)            (((x) & GENMASK(16, 16)) >> 16)

#define QSPI_QSPI_IDR_CSRA_IDR(x)                (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_IDR_CSRA_IDR_M                 GENMASK(15, 15)
#define QSPI_QSPI_IDR_CSRA_IDR_X(x)              (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_IDR_CSFA_IDR(x)                (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_IDR_CSFA_IDR_M                 GENMASK(14, 14)
#define QSPI_QSPI_IDR_CSFA_IDR_X(x)              (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_IDR_QITR_IDR(x)                (((x) << 13) & GENMASK(13, 13))
#define QSPI_QSPI_IDR_QITR_IDR_M                 GENMASK(13, 13)
#define QSPI_QSPI_IDR_QITR_IDR_X(x)              (((x) & GENMASK(13, 13)) >> 13)

#define QSPI_QSPI_IDR_QITF_IDR(x)                (((x) << 12) & GENMASK(12, 12))
#define QSPI_QSPI_IDR_QITF_IDR_M                 GENMASK(12, 12)
#define QSPI_QSPI_IDR_QITF_IDR_X(x)              (((x) & GENMASK(12, 12)) >> 12)

#define QSPI_QSPI_IDR_LWRA_IDR(x)                (((x) << 11) & GENMASK(11, 11))
#define QSPI_QSPI_IDR_LWRA_IDR_M                 GENMASK(11, 11)
#define QSPI_QSPI_IDR_LWRA_IDR_X(x)              (((x) & GENMASK(11, 11)) >> 11)

#define QSPI_QSPI_IDR_INSTRE_IDR(x)              (((x) << 10) & GENMASK(10, 10))
#define QSPI_QSPI_IDR_INSTRE_IDR_M               GENMASK(10, 10)
#define QSPI_QSPI_IDR_INSTRE_IDR_X(x)            (((x) & GENMASK(10, 10)) >> 10)

#define QSPI_QSPI_IDR_CSR_IDR(x)                 (((x) << 8) & GENMASK(8, 8))
#define QSPI_QSPI_IDR_CSR_IDR_M                  GENMASK(8, 8)
#define QSPI_QSPI_IDR_CSR_IDR_X(x)               (((x) & GENMASK(8, 8)) >> 8)

#define QSPI_QSPI_IDR_OVRES_IDR(x)               (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_IDR_OVRES_IDR_M                GENMASK(3, 3)
#define QSPI_QSPI_IDR_OVRES_IDR_X(x)             (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_IDR_TXEMPTY_IDR(x)             (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_IDR_TXEMPTY_IDR_M              GENMASK(2, 2)
#define QSPI_QSPI_IDR_TXEMPTY_IDR_X(x)           (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_IDR_TDRE_IDR(x)                (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_IDR_TDRE_IDR_M                 GENMASK(1, 1)
#define QSPI_QSPI_IDR_TDRE_IDR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_IDR_RDRF_IDR(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_IDR_RDRF_IDR_M                 GENMASK(0, 0)
#define QSPI_QSPI_IDR_RDRF_IDR_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_IMR */
#define QSPI_QSPI_IMR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 28, 0, 1, 4)

#define QSPI_QSPI_IMR_TOUT_IMR(x)                (((x) << 17) & GENMASK(17, 17))
#define QSPI_QSPI_IMR_TOUT_IMR_M                 GENMASK(17, 17)
#define QSPI_QSPI_IMR_TOUT_IMR_X(x)              (((x) & GENMASK(17, 17)) >> 17)

#define QSPI_QSPI_IMR_RFRSHD_IMR(x)              (((x) << 16) & GENMASK(16, 16))
#define QSPI_QSPI_IMR_RFRSHD_IMR_M               GENMASK(16, 16)
#define QSPI_QSPI_IMR_RFRSHD_IMR_X(x)            (((x) & GENMASK(16, 16)) >> 16)

#define QSPI_QSPI_IMR_CSRA_IMR(x)                (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_IMR_CSRA_IMR_M                 GENMASK(15, 15)
#define QSPI_QSPI_IMR_CSRA_IMR_X(x)              (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_IMR_CSFA_IMR(x)                (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_IMR_CSFA_IMR_M                 GENMASK(14, 14)
#define QSPI_QSPI_IMR_CSFA_IMR_X(x)              (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_IMR_QITR_IMR(x)                (((x) << 13) & GENMASK(13, 13))
#define QSPI_QSPI_IMR_QITR_IMR_M                 GENMASK(13, 13)
#define QSPI_QSPI_IMR_QITR_IMR_X(x)              (((x) & GENMASK(13, 13)) >> 13)

#define QSPI_QSPI_IMR_QITF_IMR(x)                (((x) << 12) & GENMASK(12, 12))
#define QSPI_QSPI_IMR_QITF_IMR_M                 GENMASK(12, 12)
#define QSPI_QSPI_IMR_QITF_IMR_X(x)              (((x) & GENMASK(12, 12)) >> 12)

#define QSPI_QSPI_IMR_LWRA_IMR(x)                (((x) << 11) & GENMASK(11, 11))
#define QSPI_QSPI_IMR_LWRA_IMR_M                 GENMASK(11, 11)
#define QSPI_QSPI_IMR_LWRA_IMR_X(x)              (((x) & GENMASK(11, 11)) >> 11)

#define QSPI_QSPI_IMR_INSTRE_IMR(x)              (((x) << 10) & GENMASK(10, 10))
#define QSPI_QSPI_IMR_INSTRE_IMR_M               GENMASK(10, 10)
#define QSPI_QSPI_IMR_INSTRE_IMR_X(x)            (((x) & GENMASK(10, 10)) >> 10)

#define QSPI_QSPI_IMR_CSR_IMR(x)                 (((x) << 8) & GENMASK(8, 8))
#define QSPI_QSPI_IMR_CSR_IMR_M                  GENMASK(8, 8)
#define QSPI_QSPI_IMR_CSR_IMR_X(x)               (((x) & GENMASK(8, 8)) >> 8)

#define QSPI_QSPI_IMR_OVRES_IMR(x)               (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_IMR_OVRES_IMR_M                GENMASK(3, 3)
#define QSPI_QSPI_IMR_OVRES_IMR_X(x)             (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_IMR_TXEMPTY_IMR(x)             (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_IMR_TXEMPTY_IMR_M              GENMASK(2, 2)
#define QSPI_QSPI_IMR_TXEMPTY_IMR_X(x)           (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_IMR_TDRE_IMR(x)                (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_IMR_TDRE_IMR_M                 GENMASK(1, 1)
#define QSPI_QSPI_IMR_TDRE_IMR_X(x)              (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_IMR_RDRF_IMR(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_IMR_RDRF_IMR_M                 GENMASK(0, 0)
#define QSPI_QSPI_IMR_RDRF_IMR_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_SCR */
#define QSPI_QSPI_SCR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 32, 0, 1, 4)

#define QSPI_QSPI_SCR_DLYBS(x)                   (((x) << 16) & GENMASK(23, 16))
#define QSPI_QSPI_SCR_DLYBS_M                    GENMASK(23, 16)
#define QSPI_QSPI_SCR_DLYBS_X(x)                 (((x) & GENMASK(23, 16)) >> 16)

#define QSPI_QSPI_SCR_CPHA(x)                    (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_SCR_CPHA_M                     GENMASK(1, 1)
#define QSPI_QSPI_SCR_CPHA_X(x)                  (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_SCR_CPOL(x)                    ((x) & GENMASK(0, 0))
#define QSPI_QSPI_SCR_CPOL_M                     GENMASK(0, 0)
#define QSPI_QSPI_SCR_CPOL_X(x)                  ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_SR */
#define QSPI_QSPI_SR(t)           __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 36, 0, 1, 4)

#define QSPI_QSPI_SR_HQSPI_VERSION(x)            (((x) << 31) & GENMASK(31, 31))
#define QSPI_QSPI_SR_HQSPI_VERSION_M             GENMASK(31, 31)
#define QSPI_QSPI_SR_HQSPI_VERSION_X(x)          (((x) & GENMASK(31, 31)) >> 31)

#define QSPI_QSPI_SR_CALBSY(x)                   (((x) << 6) & GENMASK(6, 6))
#define QSPI_QSPI_SR_CALBSY_M                    GENMASK(6, 6)
#define QSPI_QSPI_SR_CALBSY_X(x)                 (((x) & GENMASK(6, 6)) >> 6)

#define QSPI_QSPI_SR_DLOCK(x)                    (((x) << 5) & GENMASK(5, 5))
#define QSPI_QSPI_SR_DLOCK_M                     GENMASK(5, 5)
#define QSPI_QSPI_SR_DLOCK_X(x)                  (((x) & GENMASK(5, 5)) >> 5)

#define QSPI_QSPI_SR_HIDLE(x)                    (((x) << 4) & GENMASK(4, 4))
#define QSPI_QSPI_SR_HIDLE_M                     GENMASK(4, 4)
#define QSPI_QSPI_SR_HIDLE_X(x)                  (((x) & GENMASK(4, 4)) >> 4)

#define QSPI_QSPI_SR_RBUSY(x)                    (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_SR_RBUSY_M                     GENMASK(3, 3)
#define QSPI_QSPI_SR_RBUSY_X(x)                  (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_SR_CSS(x)                      (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_SR_CSS_M                       GENMASK(2, 2)
#define QSPI_QSPI_SR_CSS_X(x)                    (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_SR_QSPIENS(x)                  (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_SR_QSPIENS_M                   GENMASK(1, 1)
#define QSPI_QSPI_SR_QSPIENS_X(x)                (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_SR_SYNCBSY(x)                  ((x) & GENMASK(0, 0))
#define QSPI_QSPI_SR_SYNCBSY_M                   GENMASK(0, 0)
#define QSPI_QSPI_SR_SYNCBSY_X(x)                ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_IAR */
#define QSPI_QSPI_IAR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 48, 0, 1, 4)

/*      QSPI:QSPI_REGS:QSPI_WICR */
#define QSPI_QSPI_WICR(t)         __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 52, 0, 1, 4)

#define QSPI_QSPI_WICR_WROPT(x)                  (((x) << 16) & GENMASK(23, 16))
#define QSPI_QSPI_WICR_WROPT_M                   GENMASK(23, 16)
#define QSPI_QSPI_WICR_WROPT_X(x)                (((x) & GENMASK(23, 16)) >> 16)

#define QSPI_QSPI_WICR_WRINST(x)                 ((x) & GENMASK(15, 0))
#define QSPI_QSPI_WICR_WRINST_M                  GENMASK(15, 0)
#define QSPI_QSPI_WICR_WRINST_X(x)               ((x) & GENMASK(15, 0))

/*      QSPI:QSPI_REGS:QSPI_IFR */
#define QSPI_QSPI_IFR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 56, 0, 1, 4)

#define QSPI_QSPI_IFR_PROTTYP(x)                 (((x) << 28) & GENMASK(29, 28))
#define QSPI_QSPI_IFR_PROTTYP_M                  GENMASK(29, 28)
#define QSPI_QSPI_IFR_PROTTYP_X(x)               (((x) & GENMASK(29, 28)) >> 28)

#define QSPI_QSPI_IFR_HFWBEN(x)                  (((x) << 27) & GENMASK(27, 27))
#define QSPI_QSPI_IFR_HFWBEN_M                   GENMASK(27, 27)
#define QSPI_QSPI_IFR_HFWBEN_X(x)                (((x) & GENMASK(27, 27)) >> 27)

#define QSPI_QSPI_IFR_DDRCMDEN(x)                (((x) << 26) & GENMASK(26, 26))
#define QSPI_QSPI_IFR_DDRCMDEN_M                 GENMASK(26, 26)
#define QSPI_QSPI_IFR_DDRCMDEN_X(x)              (((x) & GENMASK(26, 26)) >> 26)

#define QSPI_QSPI_IFR_DQSEN(x)                   (((x) << 25) & GENMASK(25, 25))
#define QSPI_QSPI_IFR_DQSEN_M                    GENMASK(25, 25)
#define QSPI_QSPI_IFR_DQSEN_X(x)                 (((x) & GENMASK(25, 25)) >> 25)

#define QSPI_QSPI_IFR_APBTFRTYP(x)               (((x) << 24) & GENMASK(24, 24))
#define QSPI_QSPI_IFR_APBTFRTYP_M                GENMASK(24, 24)
#define QSPI_QSPI_IFR_APBTFRTYP_X(x)             (((x) & GENMASK(24, 24)) >> 24)

#define QSPI_QSPI_IFR_SMRM(x)                    (((x) << 23) & GENMASK(23, 23))
#define QSPI_QSPI_IFR_SMRM_M                     GENMASK(23, 23)
#define QSPI_QSPI_IFR_SMRM_X(x)                  (((x) & GENMASK(23, 23)) >> 23)

#define QSPI_QSPI_IFR_END(x)                     (((x) << 22) & GENMASK(22, 22))
#define QSPI_QSPI_IFR_END_M                      GENMASK(22, 22)
#define QSPI_QSPI_IFR_END_X(x)                   (((x) & GENMASK(22, 22)) >> 22)

#define QSPI_QSPI_IFR_NBDUM(x)                   (((x) << 16) & GENMASK(20, 16))
#define QSPI_QSPI_IFR_NBDUM_M                    GENMASK(20, 16)
#define QSPI_QSPI_IFR_NBDUM_X(x)                 (((x) & GENMASK(20, 16)) >> 16)

#define QSPI_QSPI_IFR_DDREN(x)                   (((x) << 15) & GENMASK(15, 15))
#define QSPI_QSPI_IFR_DDREN_M                    GENMASK(15, 15)
#define QSPI_QSPI_IFR_DDREN_X(x)                 (((x) & GENMASK(15, 15)) >> 15)

#define QSPI_QSPI_IFR_CRM(x)                     (((x) << 14) & GENMASK(14, 14))
#define QSPI_QSPI_IFR_CRM_M                      GENMASK(14, 14)
#define QSPI_QSPI_IFR_CRM_X(x)                   (((x) & GENMASK(14, 14)) >> 14)

#define QSPI_QSPI_IFR_TFRTYP(x)                  (((x) << 12) & GENMASK(12, 12))
#define QSPI_QSPI_IFR_TFRTYP_M                   GENMASK(12, 12)
#define QSPI_QSPI_IFR_TFRTYP_X(x)                (((x) & GENMASK(12, 12)) >> 12)

#define QSPI_QSPI_IFR_ADDRL(x)                   (((x) << 10) & GENMASK(11, 10))
#define QSPI_QSPI_IFR_ADDRL_M                    GENMASK(11, 10)
#define QSPI_QSPI_IFR_ADDRL_X(x)                 (((x) & GENMASK(11, 10)) >> 10)

#define QSPI_QSPI_IFR_OPTL(x)                    (((x) << 8) & GENMASK(9, 8))
#define QSPI_QSPI_IFR_OPTL_M                     GENMASK(9, 8)
#define QSPI_QSPI_IFR_OPTL_X(x)                  (((x) & GENMASK(9, 8)) >> 8)

#define QSPI_QSPI_IFR_DATAEN(x)                  (((x) << 7) & GENMASK(7, 7))
#define QSPI_QSPI_IFR_DATAEN_M                   GENMASK(7, 7)
#define QSPI_QSPI_IFR_DATAEN_X(x)                (((x) & GENMASK(7, 7)) >> 7)

#define QSPI_QSPI_IFR_OPTEN(x)                   (((x) << 6) & GENMASK(6, 6))
#define QSPI_QSPI_IFR_OPTEN_M                    GENMASK(6, 6)
#define QSPI_QSPI_IFR_OPTEN_X(x)                 (((x) & GENMASK(6, 6)) >> 6)

#define QSPI_QSPI_IFR_ADDREN(x)                  (((x) << 5) & GENMASK(5, 5))
#define QSPI_QSPI_IFR_ADDREN_M                   GENMASK(5, 5)
#define QSPI_QSPI_IFR_ADDREN_X(x)                (((x) & GENMASK(5, 5)) >> 5)

#define QSPI_QSPI_IFR_INSTEN(x)                  (((x) << 4) & GENMASK(4, 4))
#define QSPI_QSPI_IFR_INSTEN_M                   GENMASK(4, 4)
#define QSPI_QSPI_IFR_INSTEN_X(x)                (((x) & GENMASK(4, 4)) >> 4)

#define QSPI_QSPI_IFR_WIDTH(x)                   ((x) & GENMASK(3, 0))
#define QSPI_QSPI_IFR_WIDTH_M                    GENMASK(3, 0)
#define QSPI_QSPI_IFR_WIDTH_X(x)                 ((x) & GENMASK(3, 0))

/*      QSPI:QSPI_REGS:QSPI_RICR */
#define QSPI_QSPI_RICR(t)         __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 60, 0, 1, 4)

#define QSPI_QSPI_RICR_RDOPT(x)                  (((x) << 16) & GENMASK(23, 16))
#define QSPI_QSPI_RICR_RDOPT_M                   GENMASK(23, 16)
#define QSPI_QSPI_RICR_RDOPT_X(x)                (((x) & GENMASK(23, 16)) >> 16)

#define QSPI_QSPI_RICR_RDINST(x)                 ((x) & GENMASK(15, 0))
#define QSPI_QSPI_RICR_RDINST_M                  GENMASK(15, 0)
#define QSPI_QSPI_RICR_RDINST_X(x)               ((x) & GENMASK(15, 0))

/*      QSPI:QSPI_REGS:QSPI_SMR */
#define QSPI_QSPI_SMR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 64, 0, 1, 4)

#define QSPI_QSPI_SMR_SCRKL(x)                   (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_SMR_SCRKL_M                    GENMASK(2, 2)
#define QSPI_QSPI_SMR_SCRKL_X(x)                 (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_SMR_RVDIS(x)                   (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_SMR_RVDIS_M                    GENMASK(1, 1)
#define QSPI_QSPI_SMR_RVDIS_X(x)                 (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_SMR_SCREN(x)                   ((x) & GENMASK(0, 0))
#define QSPI_QSPI_SMR_SCREN_M                    GENMASK(0, 0)
#define QSPI_QSPI_SMR_SCREN_X(x)                 ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_SKR */
#define QSPI_QSPI_SKR(t)          __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 68, 0, 1, 4)

/*      QSPI:QSPI_REGS:QSPI_REFRESH */
#define QSPI_QSPI_REFRESH(t)      __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 80, 0, 1, 4)

/*      QSPI:QSPI_REGS:QSPI_WRACNT */
#define QSPI_QSPI_WRACNT(t)       __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 84, 0, 1, 4)

/*      QSPI:QSPI_REGS:QSPI_DLLCFG */
#define QSPI_QSPI_DLLCFG(t)       __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 88, 0, 1, 4)

#define QSPI_QSPI_DLLCFG_RANGE(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_DLLCFG_RANGE_M                 GENMASK(0, 0)
#define QSPI_QSPI_DLLCFG_RANGE_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_PCALCFG */
#define QSPI_QSPI_PCALCFG(t)      __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 92, 0, 1, 4)

#define QSPI_QSPI_PCALCFG_CALN(x)                (((x) << 28) & GENMASK(31, 28))
#define QSPI_QSPI_PCALCFG_CALN_M                 GENMASK(31, 28)
#define QSPI_QSPI_PCALCFG_CALN_X(x)              (((x) & GENMASK(31, 28)) >> 28)

#define QSPI_QSPI_PCALCFG_CALP(x)                (((x) << 24) & GENMASK(27, 24))
#define QSPI_QSPI_PCALCFG_CALP_M                 GENMASK(27, 24)
#define QSPI_QSPI_PCALCFG_CALP_X(x)              (((x) & GENMASK(27, 24)) >> 24)

#define QSPI_QSPI_PCALCFG_CALCNT(x)              (((x) << 8) & GENMASK(16, 8))
#define QSPI_QSPI_PCALCFG_CALCNT_M               GENMASK(16, 8)
#define QSPI_QSPI_PCALCFG_CALCNT_X(x)            (((x) & GENMASK(16, 8)) >> 8)

#define QSPI_QSPI_PCALCFG_CLKDIV(x)              (((x) << 4) & GENMASK(6, 4))
#define QSPI_QSPI_PCALCFG_CLKDIV_M               GENMASK(6, 4)
#define QSPI_QSPI_PCALCFG_CLKDIV_X(x)            (((x) & GENMASK(6, 4)) >> 4)

#define QSPI_QSPI_PCALCFG_DIFFPM(x)              (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_PCALCFG_DIFFPM_M               GENMASK(2, 2)
#define QSPI_QSPI_PCALCFG_DIFFPM_X(x)            (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_PCALCFG_DAPCAL(x)              (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_PCALCFG_DAPCAL_M               GENMASK(1, 1)
#define QSPI_QSPI_PCALCFG_DAPCAL_X(x)            (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_PCALCFG_AAON(x)                ((x) & GENMASK(0, 0))
#define QSPI_QSPI_PCALCFG_AAON_M                 GENMASK(0, 0)
#define QSPI_QSPI_PCALCFG_AAON_X(x)              ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_PCALBP */
#define QSPI_QSPI_PCALBP(t)       __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 96, 0, 1, 4)

#define QSPI_QSPI_PCALBP_CALNBP(x)               (((x) << 16) & GENMASK(19, 16))
#define QSPI_QSPI_PCALBP_CALNBP_M                GENMASK(19, 16)
#define QSPI_QSPI_PCALBP_CALNBP_X(x)             (((x) & GENMASK(19, 16)) >> 16)

#define QSPI_QSPI_PCALBP_CALPBP(x)               (((x) << 8) & GENMASK(11, 8))
#define QSPI_QSPI_PCALBP_CALPBP_M                GENMASK(11, 8)
#define QSPI_QSPI_PCALBP_CALPBP_X(x)             (((x) & GENMASK(11, 8)) >> 8)

#define QSPI_QSPI_PCALBP_BPEN(x)                 ((x) & GENMASK(0, 0))
#define QSPI_QSPI_PCALBP_BPEN_M                  GENMASK(0, 0)
#define QSPI_QSPI_PCALBP_BPEN_X(x)               ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_TOUT */
#define QSPI_QSPI_TOUT(t)         __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 100, 0, 1, 4)

#define QSPI_QSPI_TOUT_TCNTM(x)                  ((x) & GENMASK(15, 0))
#define QSPI_QSPI_TOUT_TCNTM_M                   GENMASK(15, 0)
#define QSPI_QSPI_TOUT_TCNTM_X(x)                ((x) & GENMASK(15, 0))

/*      QSPI:QSPI_REGS:QSPI_DEBUG */
#define QSPI_QSPI_DEBUG(t)        __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 208, 0, 1, 4)

#define QSPI_QSPI_DEBUG_DERT(x)                  (((x) << 3) & GENMASK(3, 3))
#define QSPI_QSPI_DEBUG_DERT_M                   GENMASK(3, 3)
#define QSPI_QSPI_DEBUG_DERT_X(x)                (((x) & GENMASK(3, 3)) >> 3)

#define QSPI_QSPI_DEBUG_FERR(x)                  (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_DEBUG_FERR_M                   GENMASK(2, 2)
#define QSPI_QSPI_DEBUG_FERR_X(x)                (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_DEBUG_FAHBL(x)                 (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_DEBUG_FAHBL_M                  GENMASK(1, 1)
#define QSPI_QSPI_DEBUG_FAHBL_X(x)               (((x) & GENMASK(1, 1)) >> 1)

/*      QSPI:QSPI_REGS:QSPI_WPMR */
#define QSPI_QSPI_WPMR(t)         __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 228, 0, 1, 4)

#define QSPI_QSPI_WPMR_WPKEY(x)                  (((x) << 8) & GENMASK(31, 8))
#define QSPI_QSPI_WPMR_WPKEY_M                   GENMASK(31, 8)
#define QSPI_QSPI_WPMR_WPKEY_X(x)                (((x) & GENMASK(31, 8)) >> 8)

#define QSPI_QSPI_WPMR_WPCREN(x)                 (((x) << 2) & GENMASK(2, 2))
#define QSPI_QSPI_WPMR_WPCREN_M                  GENMASK(2, 2)
#define QSPI_QSPI_WPMR_WPCREN_X(x)               (((x) & GENMASK(2, 2)) >> 2)

#define QSPI_QSPI_WPMR_WPITEN(x)                 (((x) << 1) & GENMASK(1, 1))
#define QSPI_QSPI_WPMR_WPITEN_M                  GENMASK(1, 1)
#define QSPI_QSPI_WPMR_WPITEN_X(x)               (((x) & GENMASK(1, 1)) >> 1)

#define QSPI_QSPI_WPMR_WPEN(x)                   ((x) & GENMASK(0, 0))
#define QSPI_QSPI_WPMR_WPEN_M                    GENMASK(0, 0)
#define QSPI_QSPI_WPMR_WPEN_X(x)                 ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_WPSR */
#define QSPI_QSPI_WPSR(t)         __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 232, 0, 1, 4)

#define QSPI_QSPI_WPSR_WPVSRC(x)                 (((x) << 8) & GENMASK(15, 8))
#define QSPI_QSPI_WPSR_WPVSRC_M                  GENMASK(15, 8)
#define QSPI_QSPI_WPSR_WPVSRC_X(x)               (((x) & GENMASK(15, 8)) >> 8)

#define QSPI_QSPI_WPSR_WPVS(x)                   ((x) & GENMASK(0, 0))
#define QSPI_QSPI_WPSR_WPVS_M                    GENMASK(0, 0)
#define QSPI_QSPI_WPSR_WPVS_X(x)                 ((x) & GENMASK(0, 0))

/*      QSPI:QSPI_REGS:QSPI_VERSION */
#define QSPI_QSPI_VERSION(t)      __REG(TARGET_QSPI,\
					t, 3, 0, 0, 1, 256, 252, 0, 1, 4)

#define QSPI_QSPI_VERSION_MFN(x)                 (((x) << 16) & GENMASK(18, 16))
#define QSPI_QSPI_VERSION_MFN_M                  GENMASK(18, 16)
#define QSPI_QSPI_VERSION_MFN_X(x)               (((x) & GENMASK(18, 16)) >> 16)

#define QSPI_QSPI_VERSION_VERSION(x)             ((x) & GENMASK(11, 0))
#define QSPI_QSPI_VERSION_VERSION_M              GENMASK(11, 0)
#define QSPI_QSPI_VERSION_VERSION_X(x)           ((x) & GENMASK(11, 0))


#endif /* _LAN966X_SPI_REGS_SR_H_ */
